name: Release

on:
  # dry run
  pull_request:
    branches:
      - main
    types:
      - open
      - synchronize
      - reopened
      - edited
  # actual release
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release (dry-run)
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [dry-run]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Run tests
        run: go test -json ./... > tests.json

      - name: Summarize tests
        if: always()
        uses: guyarb/golang-test-annotations@master
        with:
          test-results: tests.json

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          VERSION: ${{ needs.dry-run.outputs.new_release_version }}
        run: |
          go build \
            -ldflags "-X main.Version=${VERSION}" \
            -o tf-summarize \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-summarize
          path: tf-summarize
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-summarize
          path: release-artifacts

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.semantic.outputs.new_release_version }}
          files: release-artifacts/tf-summarize
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
